name: Sync Test Branch to S3

on:
  push:
    branches:
    - test

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Sync
      run: |
        aws cloudformation package --template-file cloudformation/BillingMetrics-Template.yaml --s3-bucket ${S3_BUCKET} \
          --s3-prefix aws-account-automation/lambda-transform --output-template-file cloudformation/BillingMetrics-Template-Transformed.yaml  \
          --metadata build_ver=$(git rev-parse --short "$GITHUB_SHA")

        aws s3 sync --delete cloudformation/ s3://${S3_BUCKET}/aws-account-automation/
      env:
        S3_BUCKET: pht-cloudformation-dev
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'